#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
OrdererOrgs:
  # - Name: Orderer
  #   Domain: example.com
  #   Specs:
  #     - Hostname: orderer
  #   Template:
  #     Count: 3

PeerOrgs:
  # - Name: Org1
  #   Domain: org1.example.com
  #   CA:
  #      Hostname: ca # implicitly ca.org1.example.com
  #   Template:
  #     Count: 2
  #     SANS:
  #       - "localhost"
  #   Users:
  #     Count: 1
  # - Name: Org2
  #   Domain: org2.example.com
  #   CA:
  #      Hostname: ca # implicitly ca.org2.example.com
  #   Template:
  #     Count: 2
  #     SANS:
  #       - "localhost"
  #   Users:
  #     Count: 1
  - Name: Org3
    Domain: org3.example.com
    CA:
       Hostname: ca # implicitly ca.org3.example.com
    Template:
      Count: 2
      SANS:
        - "localhost"
    Users:
      Count: 1
